apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: sp-cache
  namespace: default
spec:
  selector:
    matchLabels:
      app: productpage
  url: https://download.softprobe.ai/wasm/sp_istio_cache.wasm
  sha256: a1b2c3d4e5f6789012345678901234567890123456789012345678901234567890  # Update with actual hash
  phase: AUTHN
  pluginConfig:
    softprobe_endpoint: "https://o.softprobe.ai"
    cache_enabled: true
    log_level: "info"