---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: sp-istio-agent
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: demo-ota
  url: http://host.docker.internal:8000/sp_istio_agent.wasm
  sha256: 48a0943e73d55010470a1e40ddf92265fb40e61baccb062235ab2127f03b3517
  phase: AUTHN
  match:
    - mode: SERVER
    - mode: CLIENT
  pluginConfig:
    service_name: "demo-ota-1"
    api_key: "demo-ota-01"
    sp_backend_url: "https://jaeger.softprobe.ai/"
    enable_inject: false
    collectionRules:
      http:
        server:
          - path: ".*"
        client:
          - host: ".*"
            paths: [".*"]
  vmConfig:
    env:
      - name: ENVOY_LOG_LEVEL
        value: "debug"
      - name: WASM_LOG_LEVEL
        value: "debug"
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: softprobe-backend
  namespace: istio-system
spec:
  hosts:
  - jaeger.softprobe.ai
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  - number: 14268
    name: jaeger-collector
    protocol: HTTP
  location: MESH_EXTERNAL
  resolution: DNS


