# SERVER模式 - 部署在demo-airline上收集入站流量
---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: sp-istio-agent-server
  namespace: istio-system
spec:
  url: http://host.docker.internal:8000/target/wasm32-unknown-unknown/release/sp_istio_agent.wasm
  sha256: 52c2ec7f121140c80f25d8276d20a598957c56817c3ba62a654689aa4bae51a9
  phase: AUTHN
  match:
    - mode: SERVER
  pluginConfig:
    service_name: "demo-airline"
    api_key: "demo-airline-01"
    sp_backend_url: "https://jaeger.softprobe.ai"
    enable_inject: false
    traffic_direction: "server"
    collectionRules:
      http:
        server:
          - path: ".*"
        client:
          - host: ".*"
            paths: [".*"]
  vmConfig:
    env:
      - name: ENVOY_LOG_LEVEL
        value: "debug"
      - name: WASM_LOG_LEVEL
        value: "debug"
---
# CLIENT模式 - 部署在demo-ota上收集出站流量
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: sp-istio-agent-client
  namespace: istio-system
spec:
  url: http://host.docker.internal:8000/target/wasm32-unknown-unknown/release/sp_istio_agent.wasm
  sha256: 52c2ec7f121140c80f25d8276d20a598957c56817c3ba62a654689aa4bae51a9
  phase: AUTHN
  match:
    - mode: CLIENT
  pluginConfig:
    service_name: "demo-ota"
    api_key: "demo-ota-01"
    sp_backend_url: "https://jaeger.softprobe.ai"
    enable_inject: false
    traffic_direction: "client"
    collectionRules:
      http:
        server:
          - path: ".*"
        client:
          - host: ".*"
            paths: [".*"]
  vmConfig:
    env:
      - name: ENVOY_LOG_LEVEL
        value: "debug"
      - name: WASM_LOG_LEVEL
        value: "debug"
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: softprobe-backend
  namespace: istio-system
spec:
  hosts:
  - jaeger.softprobe.ai
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  - number: 80
    name: http
    protocol: HTTP
  location: MESH_EXTERNAL
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: softprobe-backend-tls
  namespace: istio-system
spec:
  host: jaeger.softprobe.ai
  trafficPolicy:
    tls:
      mode: SIMPLE


