---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: sp-istio-agent
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: demo-ota
  url: http://host.docker.internal:8000/sp_istio_agent.wasm
  sha256: 37557e6c6ce66459d22df6e41efbeb4adf81a7d8554284a2f7fefc965d252b77
  phase: AUTHN
  match:
    - mode: SERVER
    - mode: CLIENT
  pluginConfig:
    service_name: "demo-ota-11111"
    api_key: "demo-ota-0111"
    sp_backend_url: "https://o.softprobe.ai"
    enable_inject: false
    collectionRules:
      http:
        server:
          - path: ".*"
        client:
          - host: ".*"
            paths: [".*"]
  vmConfig:
    env:
      - name: ENVOY_LOG_LEVEL
        value: "debug"
      - name: WASM_LOG_LEVEL
        value: "debug"
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: softprobe-backend
  namespace: istio-system
spec:
  hosts:
  - jaeger.softprobe.ai
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  location: MESH_EXTERNAL
  resolution: DNS


