---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: sp-istio-agent
  namespace: istio-system
spec:
  url: http://host.docker.internal:8000/sp_istio_agent.wasm
  # sha256: "<digest>"  # optional, recommended for production pinning
  phase: AUTHN
  pluginConfig:
    sp_backend_url: "http://host.docker.internal:4318"
    traffic_direction: "outbound"
    enable_inject: false

---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: softprobe-backend
  namespace: istio-system
spec:
  hosts:
  - o.softprobe.ai
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  location: MESH_EXTERNAL
  resolution: DNS


