apiVersion: v1
kind: ConfigMap
metadata:
  name: istio
  namespace: istio-system
data:
  mesh: |
    defaultConfig:
      discoveryRefreshDelay: 10s
      proxyStatsMatcher:
        exclusionRegexps:
        - .*outlier_detection.*
        - .*circuit_breakers.*
        - .*upstream_rq_retry.*
        - .*upstream_rq_pending.*
        - .*_cx_.*
      tracing:
        opentelemetry:
          port: 4318
          service: host.docker.internal
    defaultProviders:
      tracing:
      - otel-tracing
    enablePrometheusMerge: true
    extensionProviders:
    - name: otel-tracing
      opentelemetry:
        service: host.docker.internal
        port: 4318
        http:
          path: /v1/traces
          timeout: 10s
        resource_detectors:
          environment: {}
    rootNamespace: istio-system
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'