---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: sp-istio-agent
  namespace: istio-system
spec:
  url: http://host.docker.internal:8000/sp_istio_agent.wasm
  sha256: "a91df8cc651e7557bd146cdf83fffef1e4fe4a37165adcc3da47fd31ecfa91a3"  # optional, recommended for production pinning
  phase: AUTHN
  pluginConfig:
    sp_backend_url: "http://host.docker.internal:4318"
    traffic_direction: "outbound"
    enable_inject: false

---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: softprobe-backend
  namespace: istio-system
spec:
  hosts:
  - host.docker.internal
  ports:
  - number: 4318
    name: http
    protocol: HTTP
  location: MESH_EXTERNAL
  resolution: DNS


