---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: sp-istio-agent
  namespace: istio-system
spec:
  url: oci://docker.io/softprobe/sp-istio-wasm:v1.0.13-https
  # sha256: "<digest>"  # optional, recommended for production pinning
  phase: AUTHN
  pluginConfig:
    sp_backend_url: "https://o.softprobe.ai"
    traffic_direction: "outbound"

---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: softprobe-backend
  namespace: istio-system
spec:
  hosts:
  - o.softprobe.ai
  - jaeger.softprobe.ai
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  - number: 80
    name: http
    protocol: HTTP
  location: MESH_EXTERNAL
  resolution: DNS


